version: "3"
services:
  web:
    build:
      context: .
      network: host
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "5100:5100"
